///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.h
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2024-11-04 08:32:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/port/cameradata.h"
#include "sensor/aa/port/lidardata.h"
 
#include "para/swc/port_pool.h"
 
namespace sensor
{
namespace aa
{
 
class Sensor
{
public:
    /// @brief Constructor
    Sensor();
    
    /// @brief Destructor
    ~Sensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();
 
private:
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Sensor.CameraData}
    std::shared_ptr<sensor::aa::port::CameraData> m_CameraData;
    
    /// @brief Instance of Port {Sensor.LidarData}
    std::shared_ptr<sensor::aa::port::LidarData> m_LidarData;
};
 
} /// namespace aa
} /// namespace sensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H