///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.h
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2024-11-01 13:31:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/port/rawdata.h"
 
#include "para/swc/port_pool.h"

#include <iostream>
#include <fstream>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <cstring>
#include <opencv2/opencv.hpp>
#include <vector>
#include <chrono>
#include <cstdint>
 
namespace sensor
{
namespace aa
{
 
class Sensor
{
public:
    /// @brief Constructor
    Sensor();
    
    /// @brief Destructor
    ~Sensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();

    std::string udp_ip;
    int udp_port;
    int sock;
    int opt;
    sockaddr_in addr;
    std::string data_path;
    std::chrono::_V2::system_clock::time_point last_save_time;
    std::chrono::seconds save_interval;
 
private:
    /// @brief Run software component
    void Run();

    void TaskGenerateREventValue();

    void save_data(
        double timestamp, 
        const std::vector<uint8_t> &left_image, 
        const std::vector<uint8_t> &right_image, 
        const std::vector<float> &lidar_data);
    void save_lidar_data(
        const std::vector<float> &lidar_data, 
        double timestamp);
    void save_camera_data(
        const std::vector<uint8_t> &img_bytes, 
        double timestamp, 
        const std::string &camera_name);


private:
    bool m_running;
    
    bool m_simulation;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Sensor.RawData}
    std::shared_ptr<sensor::aa::port::RawData> m_RawData;
};
 
} /// namespace aa
} /// namespace sensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H