///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensorfusion.cpp
/// SOFTWARE COMPONENT NAME           : SensorFusion
/// GENERATED DATE                    : 2024-11-04 08:32:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/sensorfusion.h"
 
namespace sensorfusion
{
namespace aa
{
 
SensorFusion::SensorFusion()
    : m_logger(ara::log::CreateLogger("SENF", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(4)
{
}
 
SensorFusion::~SensorFusion()
{
}
 
bool SensorFusion::Initialize()
{
    m_logger.LogVerbose() << "SensorFusion::Initialize";
    
    bool init{true};
    
    m_CameraData = std::make_shared<sensorfusion::aa::port::CameraData>();
    m_FusionData = std::make_shared<sensorfusion::aa::port::FusionData>();
    m_LidarData = std::make_shared<sensorfusion::aa::port::LidarData>();
    m_SimulationData = std::make_shared<sensorfusion::aa::port::SimulationData>();
    
    return init;
}
 
void SensorFusion::Start()
{
    m_logger.LogVerbose() << "SensorFusion::Start";
    
    m_CameraData->Start();
    m_FusionData->Start();
    m_LidarData->Start();
    m_SimulationData->Start();
    
    // run software component
    Run();
}
 
void SensorFusion::Terminate()
{
    m_logger.LogVerbose() << "SensorFusion::Terminate";
    
    m_CameraData->Terminate();
    m_FusionData->Terminate();
    m_LidarData->Terminate();
    m_SimulationData->Terminate();
}
 
void SensorFusion::Run()
{
    m_logger.LogVerbose() << "SensorFusion::Run";
    
    m_workers.Async([this] { m_CameraData->ReceiveEventCEventCyclic(); });
    m_workers.Async([this] { m_FusionData->SendEventFEventCyclic(); });
    m_workers.Async([this] { m_LidarData->ReceiveEventLEventCyclic(); });
    m_workers.Async([this] { m_SimulationData->ReceiveEventSEventCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace sensorfusion
