///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : simulationdata.cpp
/// SOFTWARE COMPONENT NAME           : SimulationData
/// GENERATED DATE                    : 2024-11-04 08:32:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "simulator/aa/port/simulationdata.h"
 
namespace deepracer
{
namespace service
{
namespace simdata
{
namespace skeleton
{
 
SvSimulationDataSkeletonImpl::SvSimulationDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvSimulationDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SIMT", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace simdata
} /// namespace service
} /// namespace deepracer

namespace simulator
{
namespace aa
{
namespace port
{
 
SimulationData::SimulationData()
    : m_logger(ara::log::CreateLogger("SIMT", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_SEventData{0.0f, 0.0f, 0.0f}
{
}
 
SimulationData::~SimulationData()
{
}
 
void SimulationData::Start()
{
    m_logger.LogVerbose() << "SimulationData::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Simulator/AA/SimulationData"};
    m_interface = std::make_shared<deepracer::service::simdata::skeleton::SvSimulationDataSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "SimulationData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "SimulationData::Start::OfferService::" << offer.Error().Message();
    }
}
 
void SimulationData::Terminate()
{
    m_logger.LogVerbose() << "SimulationData::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "SimulationData::Terminate::StopOfferService";
}
 
void SimulationData::WriteDataSEvent(const deepracer::service::simdata::skeleton::events::SEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_SEventData = data;
}
 
void SimulationData::SendEventSEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->SEvent.Send(m_SEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "SimulationData::SendEventSEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "SimulationData::SendEventSEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void SimulationData::SendEventSEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->SEvent.Send(m_SEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "SimulationData::SendEventSEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "SimulationData::SendEventSEventTriggered::Send::" << send.Error().Message();
    }
}
 
void SimulationData::SendEventSEventTriggered(const deepracer::service::simdata::skeleton::events::SEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_SEventData = data;
    auto send = m_interface->SEvent.Send(m_SEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "SimulationData::SendEventSEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "SimulationData::SendEventSEventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace simulator
 
/// EOF