///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : calc.h
/// SOFTWARE COMPONENT NAME           : Calc
/// GENERATED DATE                    : 2024-11-14 15:25:13
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_CALC_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_CALC_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "calc/aa/port/controldata.h"
#include "calc/aa/port/rawdata.h"
 
#include "para/swc/port_pool.h"
 
namespace calc
{
namespace aa
{
 
class Calc
{
public:
    /// @brief Constructor
    Calc();
    
    /// @brief Destructor
    ~Calc();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();

    void TaskReceiveREventCyclic();

// RawData 이벤트 수신 처리 함수
    void OnReceiveREvent(const deepracer::service::rawdata::proxy::events::REvent::SampleType &sample);
 
private:
    bool m_running;

    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Calc.ControlData}
    std::shared_ptr<calc::aa::port::ControlData> m_ControlData;
    
    /// @brief Instance of Port {Calc.RawData}
    std::shared_ptr<calc::aa::port::RawData> m_RawData;
};
 
} /// namespace aa
} /// namespace calc
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_CALC_AA_H