#!/bin/bash

cd `dirname $0`
source ./ngrok-env
ssh deepracer@$NGROK_ADDR -o StrictHostKeychecking=no -p $NGROK_PORT -i ./ssh-key.pem '
    cd ~/carina
    git pull

    export PARA_SDK=$PWD/work
    export PARA_CORE=$PARA_SDK
    export PARA_CONF=$PARA_SDK/etc
    export PARA_APPL=$PARA_SDK/opt
    export PARA_DATA=$PARA_SDK/var
    export LD_LIBRARY_PATH=$PARA_SDK/lib

    cd project
    cmake -B build -D CMAKE_INSTALL_PREFIX=$PARA_SDK
    cmake --build build -j $(nproc)
    cmake --install build

    cd $PARA_SDK/bin

    # kill EM process if it is already running
    pkill -f EM
    ./EM
'