///////////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.
///
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : actuator.cpp
/// SOFTWARE COMPONENT NAME           : Actuator
/// GENERATED DATE                    : 2024-11-01 13:31:52
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "actuator/aa/actuator.h"

namespace actuator
{
    namespace aa
    {

        Actuator::Actuator()
            : m_logger(ara::log::CreateLogger("ACTR", "SWC", ara::log::LogLevel::kVerbose)), m_workers(1), m_running(false)
        {
        }

        Actuator::~Actuator()
        {
        }

        bool Actuator::Initialize()
        {
            m_logger.LogVerbose() << "Actuator::Initialize";

            bool init{true};

            m_ControlData = std::make_shared<actuator::aa::port::ControlData>();

            return init;
        }

        void Actuator::Start()
        {
            m_logger.LogVerbose() << "Actuator::Start";

            m_ControlData->Start();

            // run software component
            Run();
        }

        void Actuator::Terminate()
        {
            m_logger.LogVerbose() << "Actuator::Terminate";

            m_running = false;

            m_ControlData->Terminate();
        }

        void Actuator::Run()
        {
            m_logger.LogVerbose() << "Actuator::Run";

            m_running = true;

            m_workers.Async([this]
                            { TaskReceiveCEventCyclic(); });

            m_workers.Wait();
        }
        void Actuator::TaskReceiveCEventCyclic()
        {
            m_ControlData->SetReceiveEventCEventHandler([this](const auto &sample)
                                                        { OnReceiveCEvent(sample); });
            m_ControlData->ReceiveEventCEventCyclic();
        }

        void Actuator::OnReceiveCEvent(const deepracer::service::controldata::proxy::events::CEvent::SampleType &sample)
        {
            m_logger.LogInfo() << "Actuator::OnReceiveCEvent - data size = " << sample.size();
        }
    } /// namespace aa
} /// namespace actuator
