///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : simulationdata.h
/// SOFTWARE COMPONENT NAME           : SimulationData
/// GENERATED DATE                    : 2024-11-04 08:32:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SIMULATOR_AA_SIMULATIONDATA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SIMULATOR_AA_SIMULATIONDATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/simdata/svsimulationdata_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace simdata
{
namespace skeleton
{
 
class SvSimulationDataSkeletonImpl : public SvSimulationDataSkeleton
{
public:
    /// @brief Constructor
    SvSimulationDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace simdata
} /// namespace service
} /// namespace deepracer

namespace simulator
{
namespace aa
{
namespace port
{
 
class SimulationData
{
public:
    /// @brief Constructor
    SimulationData();
    
    /// @brief Destructor
    ~SimulationData();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, SEvent
    void WriteDataSEvent(const deepracer::service::simdata::skeleton::events::SEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, SEvent
    void SendEventSEventCyclic();
     
    /// @brief Send event directly from buffer data, SEvent
    void SendEventSEventTriggered();
     
    /// @brief Send event directly with argument, SEvent
    void SendEventSEventTriggered(const deepracer::service::simdata::skeleton::events::SEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::simdata::skeleton::SvSimulationDataSkeletonImpl> m_interface;
    
    /// @brief Data for event, SEvent
    deepracer::service::simdata::skeleton::events::SEvent::SampleType m_SEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace simulator
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SIMULATOR_AA_SIMULATIONDATA_H